#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "lxd-ui"
name = "LXD UI"
description.en = "Manage LXD containers and virtual machines from a web interface"
description.fr = "Gérer les conteneurs et machines virtuelles LXD depuis une interface web"

version = "0.22~ynh2"

maintainers = ["kay0u"]

[upstream]
license = "GPL-3.0-only"
admindoc = "https://documentation.ubuntu.com/lxd/en/latest/howto/access_ui/"
code = "https://github.com/canonical/lxd-ui"
cpe = "cpe:2.3:a:canonical:lxd"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "100M"
ram.build = "2G"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.sources.main]
    url = "https://github.com/canonical/lxd-ui/archive/refs/tags/0.22.tar.gz"
    sha256 = "5e571dedaf6d4f95b783b4131d586ea6804bc231d80752555882d21c15bd3e8c"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    # The proxy is LXD admin, visitors must never be allowed here
    main.protected = true
    main.allowed = "admins"

    [resources.ports]
    main.default = 8443

    [resources.nodejs]
    version = "22"