#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK LXD
#=================================================

_check_lxd_is_installed

#=================================================
# BUILD FROM SOURCES
#=================================================
ynh_script_progression "Building $app from sources..."

_build_ui

#=================================================
# CONFIGURE LXD
#=================================================
ynh_script_progression "Configuring LXD..."

_add_client_certificate

_set_lxd_https_address

_add_lxd_override

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
