#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REVERT THE LXD CONFIGURATION
#=================================================

# LXD may have been removed before this app
if command -v lxc > /dev/null; then
    ynh_script_progression "Reverting the LXD configuration..."

    _remove_client_certificate

    _restore_lxd_https_address
fi

_remove_lxd_override

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
